/* tslint:disable */
/* eslint-disable */
/**
 * Check Point Browse Security API
 * Unified API for Check Point Browse Security — policy management and asset visibility.  ## Authentication All endpoints require a valid CloudInfra JWT token passed as a Bearer token in the `Authorization` header.  ### Obtaining a JWT Token 1. Go to the [Infinity Portal API Keys page](https://portal.checkpoint.com/dashboard/settings/api-keys). 2. Click **New** → **New Account API Key**. 3. In the **Service** dropdown select **Browser Security** and create the key. 4. Use the generated API key to obtain a JWT token from CloudInfra. 5. Include the JWT in every request:    ```    Authorization: Bearer <JWT_TOKEN>    ```  ## Rate Limiting Default limits vary per endpoint group. Exceeding any limit results in a 5-minute block period. 
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

